### ISSUE TITLE
Allow grid horizontal alignment

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#106]
<a href="https://github.com/jaredh159"><img src="https://avatars3.githubusercontent.com/u/7050938?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jaredh159](https://github.com/jaredh159)**
_Monday Feb 19, 2018 at 18:10 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/2663_

----

To pull this off, all you need to do is to set the width of the outer div of the grid component via an inline style.  It's height is already added this way.

The width can be derived easily from a combination of state and props (numCols, itemWidth, and gutter).

Once you have a width on that div you can use: `margin: 0 auto` to center align and `margin: 0 0 0 auto;` to right align.

Then the grid module can stop opting out of the horizontal alignment common control.

**Comment by benjamintennant** [comment]
+1 Kate Densmore ticket 182852

**Comment by postmastersteve** [comment]
+1 Samantha Culp and Rachel Thatcher ticket 182823

**Comment by benjamintennant** [comment]
+1 stepan ticket 183467

**Comment by benjamintennant** [comment]
+1 Tilman ticket 183581

**Comment by benjamintennant** [comment]
+1 Rebecca Thompson ticket 183766

**Comment by danjonlam** [comment]
+1 Pat Beaudoin ticket 184522

**Comment by postmastersteve** [comment]
+1 AnneMarie Simmons ticket 184591

**Comment by danjonlam** [comment]
+1 Matt Hudson ticket 185772

**Comment by benjamintennant** [comment]
+1 Tim Kamppinen ticket 186342

**Comment by postmastersteve** [comment]
+1 Kevin ticket 186486
