### ISSUE TITLE
Ability for blocks in library to show list of layouts

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#11]
When managing blocks some it would be helpful to see a list of the layouts in which they are present. This could be a tooltip or some kind of popup. If the layout list were links that allowed the editing of that layout, all the better.

**Comment by benjamintennant** [comment]
+1 Melissa Love from Facebook

**Comment by benjamintennant** [comment]
+ 1 Jane Johnson #180745

**Comment by lalunecreative** [comment]
Why not have the list instead be two separate lists "popular" etc showing of the same thing be changed into a icon you can click to change view? Right now, you're just viewing the content twice which isn't really needed.

- Allow you to drag and drop the order of the items in the list
- Allow you to delete blocks from the list
