### ISSUE TITLE
Ability to rename blocks in the layout 

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#12]
Right now you have to go to the block library to rename blocks. It would be easier to rename them in the block editing bar. 
![2018-05-24_13-25-23](https://user-images.githubusercontent.com/12831291/40501468-f2747836-5f55-11e8-8ac9-3aab8020fbe2.jpg)
This is especially helpful when there are multiple blocks with the same name.

**Comment by lalunecreative** [comment]
+1

**Comment by postmastersteve** [comment]
+1 Emily Henning ticket 181252
