### ISSUE TITLE
html in text editor?

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#127]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Friday Mar 09, 2018 at 16:56 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/2899_

----

None

**Comment by benjamintennant** [comment]
+1 Michael Chadwick ticket 181609 - wants to use custom HTML for specific style edits on specific text.

**Comment by benjamintennant** [comment]
+1 Samantha Culp and Rachel Thatcher ticket 181607 - wants to add shopify code to a text module

**Comment by postmastersteve** [comment]
closing, duplicate of #445
