### ISSUE TITLE
Add controls to text module for bold, italic, underline

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#13]
Users want the ability to style particular words with markup inside a text module editor:

- bold
- italic
- underline

Add these as buttons which can add the appropriate `<strong>` or `<em>` or `<span style="text-decoration: underline;">` tags to the markup.

**Comment by postmastersteve** [comment]
+1 Birthe Pollmeier ticket 181381

**Comment by lalunecreative** [comment]
Needs these too.

- Ability to select H1-H6 on highlighted text.
- Lists (bullets, etc) need to be added back in.

**Comment by postmastersteve** [comment]
Thanks @lalunecreative but GitHub issues are intended to be bite-sized features so the developers can manage them. Other feature requests should be [submitted to us](https://pro.photo/contact) instead of adding them in a comment here, thanks.

**Comment by benjamintennant** [comment]
+1 Michael Chadwick ticket 181609

**Comment by benjamintennant** [comment]
+1 Carola Contreras ticket 182748

**Comment by benjamintennant** [comment]
+1 Martin Olszewski ticket 183384

**Comment by benjamintennant** [comment]
+1 Erwin List ticket 185926

**Comment by danjonlam** [comment]
+1 Heiner Weiß ticket 185658

**Comment by benjamintennant** [comment]
+1 Marek Lukacko ticket 187171

**Comment by danjonlam** [comment]
+1 Eric Hoffland ticket 187078

**Comment by postmastersteve** [comment]
+1 Josh Goodman ticket 187930

**Comment by benjamintennant** [comment]
+1 Todd Stoilov ticket 188484

**Comment by benjamintennant** [comment]
+1 Dajuan Jones ticket 188821

**Comment by benjamintennant** [comment]
+1 Nikki van der Molen ticket 188776

**Comment by postmastersteve** [comment]
+1 Joe ticket 189158

**Comment by postmastersteve** [comment]
+1 Jess Burges ticket 189421

**Comment by benjamintennant** [comment]
+1 Michael Kormos

**Comment by benjamintennant** [comment]
+1 Dajuan Jones ticket 190122

**Comment by benjamintennant** [comment]
+1 Rob Hooper ticket 191744

**Comment by benjamintennant** [comment]
+1 Daniel LaBelle ticket 192841

**Comment by j-arens** [comment]
This was completed in 7.7.
