### ISSUE TITLE
Facebook comment integration

### ISSUE THREAD

**Issue by mdietsche** [downshiftorg/prophoto7-issues#133]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Monday Mar 12, 2018 at 14:02 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/2915_

----

None

**Comment by postmastersteve** [comment]
+1 Ingar Sørensen ticket 184549
