### ISSUE TITLE
Add controls for ordered and unordered lists in text module

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#15]
Text modules need buttons for creating ordered `<ol>` and unordered `<ul>` lists within the content.

**Comment by benjamintennant** [comment]
+1 Maria Wideman from Facebook group

**Comment by benjamintennant** [comment]
+1 Ann-Louise from Facebook group

**Comment by benjamintennant** [comment]
Duplicate of #348
