### ISSUE TITLE
NextGEN incompatibility.  Fix underscore template

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#160]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Monday Mar 19, 2018 at 16:40 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/2996_

----

None

**Comment by benjamintennant** [comment]
In P7 NextGen appears to prevent the loading of the visual builder.

**Comment by benjamintennant** [comment]
+1 Crystal Reynolds {Crystal Clear Photography, LLC} ticket 183336

**Comment by postmastersteve** [comment]
Zendesk ticket #[183736](https://prophotoblogs.zendesk.com/agent/tickets/183736) has been linked to this issue.

**Comment by danjonlam** [comment]
+1 Leah Huete ticket 184513

**Comment by benjamintennant** [comment]
+1 Chelsey ticket 185554

**Comment by benjamintennant** [comment]
+1 Diane Harvey ticket 185566

**Comment by benjamintennant** [comment]
+1 Natasha Thompson ticket 187598

**Comment by benjamintennant** [comment]
+1 Anne Deml ticket 187752

**Comment by benjamintennant** [comment]
+1 Olga Waechter ticket 188644

**Comment by benjamintennant** [comment]
+1 William Thomas ticket 188666

**Comment by benjamintennant** [comment]
+1 Janet Wolbarst ticket 188879

**Comment by danjonlam** [comment]
+1 Julie ticket 190429

**Comment by benjamintennant** [comment]
+1 Lisa Tappin ticket 191184

**Comment by benjamintennant** [comment]
+1 Kari McGill ticket 192343

**Comment by postmastersteve** [comment]
+1 Mike Cook ticket 192483

**Comment by postmastersteve** [comment]
+1 Nick Peters ticket 192525

**Comment by postmastersteve** [comment]
+1 Helen Taylor ticket 192956

**Comment by benjamintennant** [comment]
+1 April Holtan ticket 193340

**Comment by postmastersteve** [comment]
+1 Bill Murray ticket 193612

**Comment by postmastersteve** [comment]
+1 Ash ticket 193917

**Comment by benjamintennant** [comment]
+1 David Sharpe ticket 194060

**Comment by danjonlam** [comment]
+1 Andress Ribeiro ticket 194719

**Comment by benjamintennant** [comment]
+1 Shayne Galloway ticket 198050
