### ISSUE TITLE
Purge cache on WP url change

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#161]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Monday Mar 19, 2018 at 18:07 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/2998_

----

Users switching from http to https get served old cache until there is another customization change.

**Comment by postmastersteve** [comment]
+1 Missy ticket 184464
