### ISSUE TITLE
Form element max-width broken

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#182]
<a href="https://github.com/jaredh159"><img src="https://avatars3.githubusercontent.com/u/7050938?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jaredh159](https://github.com/jaredh159)**
_Monday Apr 09, 2018 at 19:09 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3106_

----

These controls have no effect:

![2018-04-09_15-08-54](https://user-images.githubusercontent.com/7050938/38517437-034b2e00-3c08-11e8-89b8-094ad9a79413.png)

**Comment by postmastersteve** [comment]
fixed in downshiftorg/prophoto#7011
