### ISSUE TITLE
Add search and filter to galleries library sidebar

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#19]
Gallery maintenance and filtering is a challenge when there are lots of galleries on a site.
(especially if the had been imported more than once in P6 or P7)

The ProPhoto Visual Builder should add a search by name box and filtering options to limit the list of galleries seen in the sidebar for faster access.

![2018-05-30_11-04-37](https://user-images.githubusercontent.com/275742/40729232-f09f32a0-63f9-11e8-9ffe-8a8dd6c05fc5.gif)

Perhaps filtering options could include:

- date (like WordPress does for posts & pages)
- gallery style (including the "Use design default" which is the default for galleries)
- number of photos
- category (see #18)
- tag (see #18)

**Comment by danjonlam** [comment]
+1 Matt Hudson ticket 184253

**Comment by postmastersteve** [comment]
closing to merge into the all-encompassing issue #678
(copied over +1s)
