### ISSUE TITLE
Default font style assignments

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#196]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Friday Apr 20, 2018 at 18:45 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3164_

----

Allow assignment of font styles to html elements (headings, paragraph, uls, etc...)

**Comment by benjamintennant** [comment]
+1 Tim Forbes ticket 187345 wants the ability to define defaults for captions and blockquotes

**Comment by benjamintennant** [comment]
+1 Whitney ticket 188457
