### ISSUE TITLE
Ability to control size of editing popup for tiles, blocks and modules

### ISSUE THREAD

**Issue by mdietsche** [downshiftorg/prophoto7-issues#198]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Friday Apr 20, 2018 at 19:09 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3166_

----

Move the tile editor sidebar into the normal sidebar and move the tile editor preview into the full screen thing like with the Layout screen

**Comment by lalunecreative** [comment]
YES. This. 1000+ Currently way too hard to see/edit what you're doing in tiles, especially if you have any tiles that are really large.

**Comment by benjamintennant** [comment]
+1 Fritz Liedtke ticket 188138 - suggests allowing for manually changing the size of the tile editor, as well.

**Comment by benjamintennant** [comment]
+1 Emily Henning ticket 191409

**Comment by benjamintennant** [comment]
#95

**Comment by benjamintennant** [comment]
+1 Sheena Gallegos ticket 194424
