### ISSUE TITLE
Need justified text option in text module

### ISSUE THREAD

**Issue by mdietsche** [downshiftorg/prophoto7-issues#199]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Friday Apr 20, 2018 at 19:10 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3167_

----

Import problem

**Comment by benjamintennant** [comment]
#6
