### ISSUE TITLE
Poor contrast in font style library/preview

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#205]
<a href="https://github.com/jaredh159"><img src="https://avatars3.githubusercontent.com/u/7050938?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jaredh159](https://github.com/jaredh159)**
_Wednesday Apr 25, 2018 at 15:10 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3188_

----

Something about the way we're calculating when to use a light background and when to use a dark is fairly off.  Look at this screenshot of font styles created from importing the very popular P6 design "Magdalena".  A common font color in this design is `#484848` which ends up with a very un-readable result:

![2018-04-25_11-07-56](https://user-images.githubusercontent.com/7050938/39254876-2b97cfee-4879-11e8-95c3-a8cc59a5e755.png)

**Comment by j-arens** [comment]
https://css-tricks.com/methods-contrasting-text-backgrounds/
