### ISSUE TITLE
Copy font style button in font style library

### ISSUE THREAD

**Issue by mdietsche** [downshiftorg/prophoto7-issues#215]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Friday Apr 27, 2018 at 19:47 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3210_

----

None

**Comment by benjamintennant** [comment]
+1 Yvonne Blume ticket 182304

**Comment by danjonlam** [comment]
+1 Mark Block ticket 187337

**Comment by benjamintennant** [comment]
+1 Michael Kormos ticket 188184

**Comment by benjamintennant** [comment]
+1 Nikki van der Molen ticket 188776

**Comment by danjonlam** [comment]
+1 Kathy Moore ticket 191114

**Comment by lalunecreative** [comment]
+How did I miss this? There should be a copy option in the font style sidebar when you hover over the font style. Would make this 100% easier.
