### ISSUE TITLE
Instagram grid needs placeholder

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#216]
<a href="https://github.com/meatwad5675"><img src="https://avatars3.githubusercontent.com/u/11544705?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meatwad5675](https://github.com/meatwad5675)**
_Friday Apr 27, 2018 at 19:49 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3211_

----

Placeholder should show intelligent text about why they might not have any images, and a link to authorization area in settings

**Comment by postmastersteve** [comment]
added in 7.6
