### ISSUE TITLE
Grid items don't link to post

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#259]
<a href="https://github.com/j-arens"><img src="https://avatars0.githubusercontent.com/u/15810037?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [j-arens](https://github.com/j-arens)**
_Tuesday May 22, 2018 at 19:49 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3360_

----

In p6 clicking anywhere on a post grid item would take you to that post page. Right now you have to click directly on the title to be taken to the post.

**Comment by postmastersteve** [comment]
Zendesk ticket #[181302](https://prophotoblogs.zendesk.com/agent/tickets/181302) has been linked to this issue.
