### ISSUE TITLE
Missing site favicon functionality

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#260]
<a href="https://github.com/j-arens"><img src="https://avatars0.githubusercontent.com/u/15810037?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [j-arens](https://github.com/j-arens)**
_Wednesday May 23, 2018 at 14:40 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3362_

----

None

**Comment by danjonlam** [comment]
+1 Katrina Cooke - ticket #181471

**Comment by benjamintennant** [comment]
+1 Yvonne Blume - facebook support group

**Comment by benjamintennant** [comment]
+1 Wendyadie ticket 182893

**Comment by danjonlam** [comment]
+1 Heather Moreau ticket 183433

**Comment by danjonlam** [comment]
+1 Anna Alexander ticket 183625

**Comment by danjonlam** [comment]
+1 Patrycjusz K Piorkowski ticket 183750

**Comment by postmastersteve** [comment]
+1 Megan Wynn ticket 183972

**Comment by postmastersteve** [comment]
+1 Jennifer Gentry ticket 184074

**Comment by postmastersteve** [comment]
+1 Viet Le ticket 184281

**Comment by danjonlam** [comment]
+1 Philip ticket 184528

**Comment by postmastersteve** [comment]
+1 Viet Le ticket 184281

**Comment by danjonlam** [comment]
+1 Stephanie Richartz ticket 185189

**Comment by benjamintennant** [comment]
+ 1 Kaylee Heemskerk from facebook

**Comment by danjonlam** [comment]
+1 Anne Deml ticket 183440

**Comment by benjamintennant** [comment]
+1 Tanya Cunningham ticket 185721

**Comment by benjamintennant** [comment]
+1 Gary Chen ticket 185624

**Comment by jacqieq** [comment]
+1 Jacqie McKenzie for www.jacqieq.com

**Comment by danjonlam** [comment]
+1 Dan Childs ticket 185829

**Comment by benjamintennant** [comment]
+1 Arlene Briones ticket 186061

**Comment by danjonlam** [comment]
+1 Kelly Tuohey ticket 186093

**Comment by postmastersteve** [comment]
+1 Kevin Heslin ticket 186186

**Comment by postmastersteve** [comment]
+1 Casey Lang ticket 186227

**Comment by danjonlam** [comment]
+1 Rachel Newell ticket 186709

**Comment by benjamintennant** [comment]
+1 Lance Shuey ticket 191005

**Comment by postmastersteve** [comment]
closing, added support for WordPress theme "Site Identity" favicon in an earlier release of ProPhoto 7
