### ISSUE TITLE
No controls for dropdown menu item vertical space between

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#269]
<a href="https://github.com/postmastersteve"><img src="https://avatars3.githubusercontent.com/u/275742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [postmastersteve](https://github.com/postmastersteve)**
_Friday May 25, 2018 at 16:28 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3377_

----

This Github issue is synchronized with Zendesk:

**Ticket ID:** [#181284](https://prophotoblogs.zendesk.com/agent/tickets/181284)
**Priority:** normal
**Group:** Developers
**Requester:** steve@pro.photo
**Organization:** DownShift
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment">Users of ProPhoto 6 were able to adjust the spacing between dropdown menu items, but P7 does not appear to provide controls for this.<br>Thus, settings from P6 dropdown spacing don't seem to apply after import:<br><br><a href="http://screenshots.pro.photo/2018-05-25_10-07-40.png" rel="noreferrer">http://screenshots.pro.photo/2018-05-25_10-07-40.png</a><br><br>Add slider controls to the <b>menu module</b> for padding above/below dropdown menu link items.<br>

<span class="collapse-signature"></span><div class="signature">
<p>Steve Post<br>
ProPhoto Support</p>
<p>Follow us for the latest ProPhoto news and updates:<br>
<a href="https://www.twitter.com/prophotoblogs/" rel="noreferrer">https://www.twitter.com/prophotoblogs/</a></p>
</div>
</div></blockquote>

**Comment by lalunecreative** [comment]
Matt Vickers - Facebook Support Group - https://www.facebook.com/groups/prophotosupportgroup/permalink/2020479458026984/

**Comment by lalunecreative** [comment]
+1 Gail Kenney (Facebook Support Group)
https://www.facebook.com/groups/prophotosupportgroup/permalink/2020479458026984/

**Comment by lalunecreative** [comment]
This issue was in P6 Here - https://github.com/downshiftorg/prophoto-issues/issues/344
Likewise to a separate ticket here - https://github.com/downshiftorg/prophoto-issues/issues/475

**Comment by lalunecreative** [comment]
+1 Maggie Collins via Facebook Support Group Message

**Comment by benjamintennant** [comment]
+1 Chris Rioux ticket 182440

**Comment by danjonlam** [comment]
+1 Cristina Depoy ticket 184712

**Comment by benjamintennant** [comment]
+1 Johnny Corcoran from Facebook

**Comment by danjonlam** [comment]
+1 Anastasiya ticket 185907
