### ISSUE TITLE
Add UI to show in which layouts a block appears

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#275]
Users see a count of the number of appearances for each block in the _Blocks_ sidebar, but they cannot see **which layouts** contain that block.

- change the color of the counter when the block appears in the current layout for quick visual reference
- add a tooltip or other UI to list the layouts in which each block appears

**Comment by postmastersteve** [comment]
+1 Jess Burges ticket 181480

**Comment by postmastersteve** [comment]
+1 Melissa Love via Facebook

**Comment by postmastersteve** [comment]
+1 Matt Hudson via Facebook

**Comment by meatwad5675** [comment]
Let's change the default color of the count circle to grey (silversand), and then show it as our green color when it is in the current layout.  Also our tooltip to the count circle with the names of each layout it is used in.

**Comment by benjamintennant** [comment]
+1 Yvonne Blume ticket 182304
