### ISSUE TITLE
Support Google Font variants in Visual Builder

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#288]
In P6 we supported some limited Google Font variants, like bold and italic. These variants look different then simply adding the italic and bold options in font style builder. Adding the P6 supported variants back in would be well received. Even more, though, having all the variants (e.g thin, thin italic, etc) available would be amazing.

**Comment by benjamintennant** [comment]
+1 Samantha Culp and Rachel Thatcher ticket 181607

**Comment by j-arens** [comment]
Duplicate #302
