### ISSUE TITLE
Grid modules missing "Number of posts" controls

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#293]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#182007](https://prophotoblogs.zendesk.com/agent/tickets/182007)
**Priority:** low
**Group:** Developers
**Requester:** josh@pro.photo
**Organization:** DownShift
**Issue escalated by:** Josh Arens

**Original ticket description:**

<blockquote><div class="zd-comment">The "Recent posts" grid type gives users the ability to control how many items appear in the grid.<br><br>But other grid types do not.<br><br><a href="http://screenshots.pro.photo/2018-05-31_12-48-23.png" rel="noreferrer">http://screenshots.pro.photo/2018-05-31_12-48-23.png</a><br><br>I suspect we are just inheriting the WordPress value from <i>"Settings &gt; Reading"</i> to determine the number of items to show, but this prevents users from achieving the look they want for their grids.<br><br>Please add controls for grid item count.<br>Steve Post<br><br>

<span class="collapse-signature"></span><div class="signature">
<p>Josh Arens<br>
ProPhoto Support</p>
<p>Follow us for the latest ProPhoto news and updates:<br>
<a href="https://www.facebook.com/prophotoblogs/" rel="noreferrer">https://www.facebook.com/prophotoblogs/</a></p>
</div>
</div></blockquote>

**Comment by benjamintennant** [comment]
+1 Yvonne Blume

**Comment by postmastersteve** [comment]
+1 Rudy Montilla ticket 183327
