### ISSUE TITLE
Archive type page settings not working

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#295]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#182009](https://prophotoblogs.zendesk.com/agent/tickets/182009)
**Priority:** normal
**Group:** Developers
**Requester:** josh@pro.photo
**Organization:** DownShift
**Issue escalated by:** Josh Arens

**Original ticket description:**

<blockquote><div class="zd-comment">I'm on a page where I notice the category archive title is not displaying. I go to edit the content module and go to "Header styles" &gt; "Archive type page heading." All but one of the settings are disabled and I can't open them with the edit icon. I'm assuming the title is hidden but I can't change it. See <a href="http://screenshots.pro.photo/2018-06-05_11-50-40.png" rel="noreferrer">http://screenshots.pro.photo/2018-06-05_11-50-40.png</a> at this url<br><br><a href="https://designs.pro.photo/east-main/category/business/?pp-visual=1#/blocks/standard/" rel="noreferrer">https://designs.pro.photo/east-main/category/business/?pp-visual=1#/blocks/standard/</a><br>

<span class="collapse-signature"></span><div class="signature">
<p>Josh Arens<br>
ProPhoto Support</p>
<p>Follow us for the latest ProPhoto news and updates:<br>
<a href="https://www.twitter.com/prophotoblogs/" rel="noreferrer">https://www.twitter.com/prophotoblogs/</a></p>
</div>
</div></blockquote>

**Comment by postmastersteve** [comment]
+1 Oliver Doran ticket 187590

**Comment by benjamintennant** [comment]
+1 Emily Brown from FB

**Comment by benjamintennant** [comment]
+1 Sarah Hilton from FB

**Comment by postmastersteve** [comment]
duplicate of #604
