### ISSUE TITLE
Ability to hide title area in content module

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#298]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#182012](https://prophotoblogs.zendesk.com/agent/tickets/182012)
**Priority:** normal
**Group:** Developers
**Requester:** josh@pro.photo
**Organization:** DownShift
**Issue escalated by:** Josh Arens

**Comment by benjamintennant** [comment]
+1 Marek Lukacko ticket 180942

**Comment by benjamintennant** [comment]
+1 Martin Olszewski ticket 183384 - wants to hide page titles - a separate option to hide gallery and/or page titles would be a good idea.

**Comment by benjamintennant** [comment]
+1 Jennifer Holland-Lloyd ticket 183887

**Comment by postmastersteve** [comment]
+1 Sandra Luoni ticket 184391

**Comment by postmastersteve** [comment]
+1 renee bell ticket 184686

**Comment by postmastersteve** [comment]
+1 Dan Rioux ticket 184705

**Comment by postmastersteve** [comment]
+1 Mike Moreland ticket 184763
