### ISSUE TITLE
Consolidate mobile menu assignment/options to prevent confusion

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#309]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#182023](https://prophotoblogs.zendesk.com/agent/tickets/182023)
**Priority:** normal
**Group:** Developers
**Requester:** josh@pro.photo
**Organization:** DownShift
**Issue escalated by:** Josh Arens

**Original ticket description:**

<blockquote><div class="zd-comment">There is confusion about how to hide/show the mobile menu. Right now, it's a layout option. Not only is the language there confusing but but having the controls there makes it so you have to make that change on every layout. If we just use the visibility controls for the slideover block (and prevent the hiding at all breakpoints) then you would only have to change it in one place. Way easier. <br><br>At the very least, in the layout &gt; mobile menu area it should give the same breakpoint options as blocks and modules. <br>

<span class="collapse-signature"></span><div class="signature">
<p>Josh Arens<br>
ProPhoto Support</p>
<p>Follow us for the latest ProPhoto news and updates:<br>
<a href="https://pro.photo/blog/" rel="noreferrer">https://pro.photo/blog/</a></p>
</div>
</div></blockquote>

**Comment by j-arens** [comment]
https://github.com/downshiftorg/prophoto7-issues/issues/327

**Comment by postmastersteve** [comment]
closing, duplicate of #339
