### ISSUE TITLE
No option for default grid/gallery style

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#314]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#182028](https://prophotoblogs.zendesk.com/agent/tickets/182028)
**Priority:** low
**Group:** Developers
**Requester:** josh@pro.photo
**Organization:** DownShift
**Issue escalated by:** Josh Arens

**Original ticket description:**

<blockquote><div class="zd-comment">When editing a gallery in <i>"Galleries &gt; All Galleries" </i>there is an option to select a gallery style for that page. It still says "use design setting." There is not currently a way to set a default for permalink or embedded galleries so we should remove this option and have it default to the first gallery... or we should add this option somewhere. <br><br><a href="http://screenshots.pro.photo/2018-05-14_20-53-18.png" rel="noreferrer">http://screenshots.pro.photo/2018-05-14_20-53-18.png</a><br>

<span class="collapse-signature"></span><div class="signature">
<p>Josh Arens<br>
ProPhoto Support</p>
<p>Follow us for the latest ProPhoto news and updates:<br>
<a href="https://pro.photo/blog/" rel="noreferrer">https://pro.photo/blog/</a></p>
</div>
</div></blockquote>

**Comment by benjamintennant** [comment]
+1 Peter Albrecht ticket 181847 - suggests an option to have a way to select a default style in the gallery style library. Click a star... drag a style to the top where it gets a "default" label... something like that.

**Comment by benjamintennant** [comment]
+1 Travis Borkenhagen ticket 186311 - doesn't like having to set the gallery style on every single gallery he inserts. He would like a default option.

**Comment by benjamintennant** [comment]
+1 Justina Bilodeau ticket 186873
