### ISSUE TITLE
Text module controls get stuck behind the block if it's at the top of the layout

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#336]

**Comment by lalunecreative** [comment]
+1. I have to adjust the block height to see the module controls in a few of our designs. It's only in modules that have been placed near the top that have a 0/0 padding or near 0 padding.

**Comment by lalunecreative** [comment]
Related/Same issue #236

**Comment by j-arens** [comment]
Duplicate of https://github.com/downshiftorg/prophoto7-issues/issues/236
