### ISSUE TITLE
Add basic WooCommerce compatibility

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#343]
Replicate the compatibility we had with ProPhoto 6 so that layout can be assigned to all WooCommerce custom post types.

**Comment by benjamintennant** [comment]
+1 Andrea ticket 182694

**Comment by benjamintennant** [comment]
+1 Candy Hoehn ticket 182332

**Comment by benjamintennant** [comment]
+1 Ben ticket 183370

**Comment by benjamintennant** [comment]
+1 Mike Moreland ticket 183422

**Comment by benjamintennant** [comment]
+1 Northfolk - wanting to sell designs that demonstrate some WC integration

**Comment by benjamintennant** [comment]
+1 Alicia Bauer ticket 184138

**Comment by benjamintennant** [comment]
+1 Marta Montilla - from Facebook support group

**Comment by benjamintennant** [comment]
+1 Jennifer Clare - from Facebook support group

**Comment by benjamintennant** [comment]
+1 Jennifer Holland-Lloyd ticket 184114

**Comment by benjamintennant** [comment]
+1 Ariel Garcia ticket 184110 - wants to create a design with WC integration

**Comment by benjamintennant** [comment]
+1 Loreta Labarca from Facebook support group

**Comment by benjamintennant** [comment]
+1 Janet Wolbarst ticket 184891

**Comment by postmastersteve** [comment]
+1 Sarah Graham ticket 185563

**Comment by benjamintennant** [comment]
+1 Sarah Henry from Facebook

**Comment by benjamintennant** [comment]
+1 Benjamin Urness ticket 185945

**Comment by benjamintennant** [comment]
+1 Benjamin Urness ticket 186355
