### ISSUE TITLE
Add List element options in Text Module

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#348]
Users would like to be able to add bulleted lists and blockquote elements

**Comment by benjamintennant** [comment]
+1 charles thorne ticket 188634

**Comment by benjamintennant** [comment]
+1 michael kormos

**Comment by benjamintennant** [comment]
+1 Don Sparks ticket 188746

**Comment by benjamintennant** [comment]
+1 Dajuan Jones ticket 190122

**Comment by postmastersteve** [comment]
+1 Philip Boudreau ticket 190932

**Comment by benjamintennant** [comment]
Duplicate of #15

**Comment by benjamintennant** [comment]
+ 1 Kaui Nichols from FB

**Comment by benjamintennant** [comment]
+1 Ann-Louise from Facebook group

**Comment by benjamintennant** [comment]
+1 Maria Wideman from Facebook group

**Comment by postmastersteve** [comment]
complete in 7.7
