### ISSUE TITLE
Add search and filter to block libraries

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#349]
Blocks have limited, pre-defined sorting options right now. The "popular blocks" option is better then "recently updated" but consider something more flexible. When you have a lot of blocks it's hard to find the right one. Even alphabetical sorting would be better. Search would be idea.

**Comment by danjonlam** [comment]
+1 Lindy Cordell Ticket 182536

**Comment by danjonlam** [comment]
+1 eric hoffland ticket 187078

**Comment by benjamintennant** [comment]
+1 Rob Hooper ticket 188156

**Comment by benjamintennant** [comment]
+1 Jay Rowden ticket 188089

**Comment by benjamintennant** [comment]
+1 Dajuan Jones ticket 188821

**Comment by benjamintennant** [comment]
+1 Anna Wisjo ticket 189936

**Comment by danjonlam** [comment]
+1 Matt Hudson ticket 190706

**Comment by benjamintennant** [comment]
#454 suggests drag-dropping which is also a good idea

**Comment by postmastersteve** [comment]
closing to merge into the all-encompassing issue #678
(copied over +1s)
