### ISSUE TITLE
Add search and filter to font library

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#350]
When you have a lot of font styles it's hard to find the right one. Even alphabetical sorting would be better. Or drag and drop? Search, too would be good.

**Comment by danjonlam** [comment]
+1 eric hoffland ticket 187078

**Comment by benjamintennant** [comment]
+1 Paul Tansley from FB

**Comment by benjamintennant** [comment]
+1 Hallie Stevenson Westcott from FB

**Comment by postmastersteve** [comment]
closing to merge into the all-encompassing issue #678
(copied over +1s)
