### ISSUE TITLE
Show actual design thumbnail in Manage Designs area

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#351]
Right now imported designs don't show the proper thumbnail. Instead they show a default ProPhoto logo image. 
![2018-06-22_15-07-58](https://user-images.githubusercontent.com/12831291/41794683-2364d7bc-762e-11e8-9d01-82e31151ddfc.jpg)

**Comment by postmastersteve** [comment]
+1 Matt Hudson ticket 184556
