### ISSUE TITLE
Option to hide sidebar in visual builder for better previewing

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#352]
It can be difficult to see what the site will really look like in the Visual Builder when on a smaller screen. An option for hiding the sidebar would help give a more accurate presentation, especially for laptop and desktop modes.

**Comment by benjamintennant** [comment]
+1 Yvonne Blume ticket 182304

**Comment by j-arens** [comment]
Duplicate of https://github.com/downshiftorg/prophoto7-issues/issues/116
