### ISSUE TITLE
Add page selector option for linkable elements

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#355]
Elements which can link to other pages currently require users to type or paste the URL manually, including the...

- graphics module
- custom grid items
- text module (when creating a link)

The UI should provide the option to either pick a page from the WordPress setup, or paste in a URL manually.

See also #692 regarding pasting links manually need to have better validation & feedback.

**Comment by postmastersteve** [comment]
+1 Bruce Dv ticket 182475

**Comment by postmastersteve** [comment]
+1 Katelynn Ponomarenko ticket 188456

**Comment by benjamintennant** [comment]
#413

**Comment by benjamintennant** [comment]
+1 Howard Angus ticket 197862

**Comment by benjamintennant** [comment]
+1 Sam ticket 216974

**Comment by mdietsche** [comment]
These areas should have a radio input with "A Page" or "A custom link" as options.  Selecting page should show a custom page dropdown (like at top of visual builder).
