### ISSUE TITLE
Add checkbox field type for multiple selections

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#368]
Users would like to be able to create a group of options which visitors can select from, allowing for one or more choices to be submitted. See older issue with comments at https://github.com/downshiftorg/prophoto-issues/issues/783

**Comment by benjamintennant** [comment]
+1 Jen Thalmann Maguire from Facebook support group

**Comment by postmastersteve** [comment]
closing - duplicate of #450
