### ISSUE TITLE
Add support for dynamic font-size values

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#373]
Customers frequently want to create font styles which can resize responsive in their layout.

E.g. text within a navigation menu to prevent stacking, heading text that should be huge in a masthead block, but shouldn't stay huge on smaller phones.

- Consider adding dynamic font size options like em, rem, %
- Consider adding breakpoint overrides for font size

**Comment by postmastersteve** [comment]
+1 Jonathan Adams ticket 183221

**Comment by benjamintennant** [comment]
+1 Tim Kamppinen ticket 186342

**Comment by postmastersteve** [comment]
+1 Charles Diehle ticket 190141

**Comment by postmastersteve** [comment]
+1 Jacquelynn Buck ticket 192052

**Comment by postmastersteve** [comment]
+1 Honey Atkinson ticket 193850

**Comment by postmastersteve** [comment]
+1 Summer Rottinger ticket 193970

**Comment by postmastersteve** [comment]
+1 Corinna Schutz ticket 193899

**Comment by postmastersteve** [comment]
+1 lana ticket 195951

**Comment by benjamintennant** [comment]
+1 Janelle Rose ticket 200622

**Comment by mdietsche** [comment]
I'm thinking font-size and font color should be override options in areas where you can select a font style.  Probably would be best to modify the font style selector to incorporate that universally in the UI.
