### ISSUE TITLE
Show correct font family names for uploaded woffs in font dropdown

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#376]
Currently, any uploaded woff file shows as "UploadedWoff-XXXX" in the Visual Builder. 
![woff_names](https://user-images.githubusercontent.com/12831291/42766352-419b9316-88e8-11e8-93b5-538ec64576bb.jpg)

Show the actual font name instead.

**Comment by benjamintennant** [comment]
+1 Chris Reichman ticket 183262

**Comment by benjamintennant** [comment]
+1 Matt Hudson ticket 187167

**Comment by postmastersteve** [comment]
+1 Josh Goodman ticket 187930

**Comment by benjamintennant** [comment]
+1 Meghan Stovall ticket 188488

**Comment by postmastersteve** [comment]
closing - fixed in 7.7
