### ISSUE TITLE
Add "number posts" customization to post category grids

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#381]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#183389](https://prophotoblogs.zendesk.com/agent/tickets/183389)
**Priority:** low
**Group:** Developers
**Requester:** josh@pro.photo
**Organization:** DownShift
**Issue escalated by:** Josh Arens

**Original ticket description:**

<blockquote><div class="zd-comment">A recent posts grid has an option called "number posts" where you can say how many posts you want in the grid. The recent posts from   category grid does not have this option. It should. This seems like a bug. It seems to default to 9 items.<br>

<span class="collapse-signature"></span><div class="signature">
<p dir="auto">Josh Arens<br>
ProPhoto Support</p>
<p dir="auto">Follow us for the latest ProPhoto news and updates:<br>
<a href="https://pro.photo/blog/" rel="noreferrer">https://pro.photo/blog/</a></p>
</div>
</div></blockquote>

**Comment by benjamintennant** [comment]
+1 Gavin Howarth ticket 183322

**Comment by benjamintennant** [comment]
Marta Montilla - from Facebook support group

**Comment by postmastersteve** [comment]
+1 Rudy Montilla ticket 183327

**Comment by danjonlam** [comment]
+1 Samantha Culp/Rachel Thatcher ticket 183729

**Comment by postmastersteve** [comment]
+1 Ariana Batz ticket 185637
