### ISSUE TITLE
Add lazy loading for images and galleries

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#388]
Add back in the lazyloading options that were present in ProPhoto 6.

**Comment by benjamintennant** [comment]
+1 Manuel Gracia ticket 183412

**Comment by pboulanov** [comment]
+1 for me too! Was just looking all around it.

**Comment by mixellita** [comment]
+1 for me too!

**Comment by postmastersteve** [comment]
+1 Jacquelyn Smith ticket 184600
