### ISSUE TITLE
Link/hover font CSS not getting applied inside of WP content module

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#395]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#183634](https://prophotoblogs.zendesk.com/agent/tickets/183634)
**Priority:** high
**Group:** Developers
**Requester:** matt@pro.photo
**Organization:** DownShift
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment">Something in the way we're using glamor to create font CSS for the WordPress content module isn't working properly.  Possibly punt this issue until we switch to new lexed font approach?<br>

<span class="collapse-signature"></span><div class="signature">
<p dir="auto">Matt Dietsche<br>
ProPhoto Support</p>
<p dir="auto">Follow us for the latest ProPhoto news and updates:<br>
<a href="https://pro.photo/blog/" rel="noreferrer">https://pro.photo/blog/</a></p>
</div>
</div></blockquote>

**Comment by postmastersteve** [comment]
+1 Leslie Taylor ticket 184440

**Comment by postmastersteve** [comment]
*Comment made from Zendesk by Steve Post on 2018-08-16 at 20:25:*

<blockquote><div class="zd-comment">using this format to add CSS to user sites:<br><br><pre style="white-space: pre-wrap">/* FIX PROBLEM #183634 */<br>.article-content a { color: #XXXXXX !important; }<br>/* END FIX */</pre>
<br>
</div></blockquote>

**Comment by danjonlam** [comment]
+1 Anne Deml ticket 183440

**Comment by danjonlam** [comment]
+1 Monica Schwartz ticket 184706

**Comment by danjonlam** [comment]
+1 Kristy Arias ticket 185080

**Comment by danjonlam** [comment]
+1 Heiner Weiß ticket 185023

**Comment by danjonlam** [comment]
+1 Paula Dietz Rauber ticket 185408

**Comment by danjonlam** [comment]
+1 Anastasiya ticket 185907

**Comment by danjonlam** [comment]
+1 Noreen Geiser ticket 186071

**Comment by danjonlam** [comment]
+1 Meghan ticket 186273

**Comment by benjamintennant** [comment]
+1 Rikki Dy-liacco ticket 186291

**Comment by danjonlam** [comment]
+1 Michael Renga ticket 186025

**Comment by benjamintennant** [comment]
+1 Rita Zlatnik ticket 188647

**Comment by benjamintennant** [comment]
+1 Dajuan Jones ticket 188821

**Comment by benjamintennant** [comment]
+ 1 from Holly Durr on facebook

**Comment by benjamintennant** [comment]
+1 Kerstin ticket 190383
