### ISSUE TITLE
layouts: make associated page names clickable links

### ISSUE THREAD

**Issue by creative-resort** [downshiftorg/prophoto7-issues#404]
When I want to edit a layout,
I don't want to be forced to 
1. tediously find out, first which page it is being used on,
2. go to the dashboard or website preview
3. navigate to that page
4. finally click "customize"

**Please make one-click editing of a layout available from the layouts overview.**

**Comment by lalunecreative** [comment]
You should submit this via the https://pro.photo/contact form, because I'm pretty sure they aren't checking github any longer, and are using tickets as their main source of tallys and checks for what people want. Everything goes through zen desk then just auto posts here I believe.

**Comment by j-arens** [comment]
Thanks for the feedback! We're going to be releasing 7.1 soon with a couple improvements focused around navigating in the customizer. We haven't implemented navigation the way your describing yet, but it's something we've talked about doing internally and would like to do sooner than later.

**Comment by postmastersteve** [comment]
closing - added to ProPhoto several versions ago
