### ISSUE TITLE
Import P5 galleries and render when embedded

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#406]
ProPhoto 6 allowed users to import ProPhoto 5 galleries. In addition, the theme could read the P5 embed, converting it to the appropriate P6 code. ProPhoto 7 currently does not do this. A gallery added in P5 that was imported into P6 does not show in the page content area in P7. Consider an import UI that is a part of onboarding to P7 or a separate "Import P5 galleries" button.

**Comment by benjamintennant** [comment]
+1 Rebecca Thompson ticket 183766

**Comment by benjamintennant** [comment]
+1 Sarah Murray ticket 187968

**Comment by benjamintennant** [comment]
+1 Fritz Liedtke ticket 188138

**Comment by benjamintennant** [comment]
+1 Jennifer Pope ticket 188153 - updating from ProPhoto 5

**Comment by benjamintennant** [comment]
Related to https://github.com/downshiftorg/prophoto7-issues/issues/587

**Comment by benjamintennant** [comment]
+1 Viktor Isaak via Facebook.

**Comment by benjamintennant** [comment]
+1 Rebecca Wilkowski ticket 189253

**Comment by benjamintennant** [comment]
+1 Lance Lanagan ticket 189363

**Comment by benjamintennant** [comment]
+1 ron espina ticket 189719

**Comment by benjamintennant** [comment]
+1 Gina Logan ticket 189755

**Comment by j-arens** [comment]
https://github.com/downshiftorg/prophoto7-issues/issues/587

**Comment by benjamintennant** [comment]
+1 Kristin Harris ticket 190154

**Comment by benjamintennant** [comment]
+1 Katerina ticket 189948

**Comment by benjamintennant** [comment]
+1 Beatriz McDonald ticket 190203 - lots of previously embedded galleries in posts in p5

**Comment by benjamintennant** [comment]
+1 Carolyn Devine ticket 191035 - lots of p5 galleries in posts

**Comment by benjamintennant** [comment]
+1 Kathy Moore ticket 191114

**Comment by lalunecreative** [comment]
+1 I've had several complaints about this one, while they're ok with losing everything else from P5, galleries has been a source of the most frustration.

**Comment by benjamintennant** [comment]
+1 Jessie Hearn ticket 192141

**Comment by benjamintennant** [comment]
+1 Adelina Leonti ticket 192868

**Comment by benjamintennant** [comment]
+1 Edina ticket 193018

**Comment by benjamintennant** [comment]
+1 Jackie Harley ticket 193110

**Comment by benjamintennant** [comment]
+1 Aubrie LeGault ticket 193334

**Comment by postmastersteve** [comment]
+1 Katie Shaw ticket 193211

**Comment by benjamintennant** [comment]
+1 Rajan Parrikar ticket 193805

**Comment by benjamintennant** [comment]
+1 Alyson Boyer Rode ticket 193927

**Comment by benjamintennant** [comment]
+1 Howard Angus ticket 194138 - coming from P4 with tons of galleries in posts
