### ISSUE TITLE
Linking Tile / Graphics like menu items

### ISSUE THREAD

**Issue by creative-resort** [downshiftorg/prophoto7-issues#413]
Please make linking of tiles and graphics the way it is possible for menu items
(by selecting the link target from a list of existing WordPress entities) available.

![2018-08-07_215029](https://user-images.githubusercontent.com/12367437/43798882-316fb66a-9a8c-11e8-84dc-2c8b050edf9a.png)
![2018-08-07_215110](https://user-images.githubusercontent.com/12367437/43798883-318e3586-9a8c-11e8-8e68-93aeb1d7d2c4.png)

**Comment by postmastersteve** [comment]
duplicate of #355
