### ISSUE TITLE
Hide page title on specific pages/posts

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#432]

**Comment by lalunecreative** [comment]
Could we keep this out of the actual wordpress page area and just add it to the builder? It's easier to just turn the page title off in the wordpress content module.

**Comment by j-arens** [comment]
https://github.com/downshiftorg/prophoto7-issues/issues/298

**Comment by postmastersteve** [comment]
duplicate of #298
