### ISSUE TITLE
Grid item images should be downsized dynamically

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#438]
Re-implement the p6 grid item approach

**Comment by postmastersteve** [comment]
Zendesk ticket #[183780](https://prophotoblogs.zendesk.com/agent/tickets/183780) has been linked to this issue.

**Comment by j-arens** [comment]
https://github.com/downshiftorg/prophoto7-issues/issues/86

**Comment by danjonlam** [comment]
+1 Thiebauld Ben lahoussine ticket 184640
