### ISSUE TITLE
Update references to URL resources whenever the site address changes

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#444]

**Comment by j-arens** [comment]
https://github.com/downshiftorg/prophoto7-issues/issues/180

**Comment by j-arens** [comment]
https://github.com/downshiftorg/prophoto7-issues/issues/161

**Comment by postmastersteve** [comment]
+1 Kristina ticket 185908

**Comment by postmastersteve** [comment]
+1 Jessica Shepard ticket 185937

**Comment by meatwad5675** [comment]
+1 Missy ticket 184464
