### ISSUE TITLE
Add checkbox input to form elements

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#450]

**Comment by j-arens** [comment]
https://github.com/downshiftorg/prophoto7-issues/issues/368

**Comment by danjonlam** [comment]
+1 Benjamin ticket 184762

**Comment by benjamintennant** [comment]
+1 Annelie Brux ticket 184926

**Comment by postmastersteve** [comment]
+1 Rob Shaw ticket 186033

**Comment by postmastersteve** [comment]
+1 Jen Thalmann Maguire from Facebook support group

**Comment by benjamintennant** [comment]
+1 Leslaw Kanikula ticket 186309
