### ISSUE TITLE
Can't make a slideover block unique

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#477]
There's a couple problems here.

Clicking to make a slideover block doesn't actually make it unique, it doesn't even unlock the block.

![2018-11-29_16-42-22](https://user-images.githubusercontent.com/15810037/49253937-dd4abd00-f3f5-11e8-911e-017a66abf8b7.gif)

After clicking the button to make the slideover block unique we stop tracking it's dirtiness correctly. Adding or removing modules from it and saving does not show the updates on the front. If you change a customization or attribute on the actual slideover block then the contents are correct on the front.

![2018-11-29_16-45-57](https://user-images.githubusercontent.com/15810037/49254132-6e219880-f3f6-11e8-9481-2fdb0c2cf930.gif)

**Comment by postmastersteve** [comment]
Zendesk ticket #[188136](https://prophotoblogs.zendesk.com/agent/tickets/188136) has been linked to this issue.
