### ISSUE TITLE
Provide opt-out of social media scripts (Facebook, Pinterest, Instagram...) for GDPR purposes

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#482]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#185067](https://prophotoblogs.zendesk.com/agent/tickets/185067)
**Priority:** high
**Group:** Developers
**Requester:** andrew@paules.org
**Assignee:** Matt Dietsche
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment">
<p dir="auto">This is a follow-up to your previous request <a href="/agent/tickets/184665" target="_blank" rel="ticket">#184665</a> "ProPhoto 7 Disable Facebook..."</p>

<p dir="auto">Hello again Dan,</p>

<p dir="auto">I replied to the signal message with more precise login info but never heard back - were yall able to get it working?</p>

<p dir="auto">Thanks!</p>
</div></blockquote>

**Comment by benjamintennant** [comment]
+1 Annett Valentin ticket 184978

**Comment by benjamintennant** [comment]
+1 Annelie Brux ticket 184926

**Comment by benjamintennant** [comment]
+1 Tilman ticket 183925

**Comment by postmastersteve** [comment]
Zendesk ticket #[185331](https://prophotoblogs.zendesk.com/agent/tickets/185331) has been linked to this issue.

**Comment by benjamintennant** [comment]
+1 Leslaw Kanikula ticket 186309
