### ISSUE TITLE
Add alternate "alt" text for all images in ProPhoto galleries and grids and excerpts

### ISSUE THREAD

**Issue by mdietsche** [downshiftorg/prophoto7-issues#488]
Currently only the preloaded images in standard and carousel galleries show their alt text. Any images loaded via javascript don't show it and neither do grid item images.

**Comment by benjamintennant** [comment]
+1 Peter Albrecht ticket 185377

**Comment by benjamintennant** [comment]
+1 Pierre Torset ticket 187227

**Comment by benjamintennant** [comment]
Related ProPhoto 6 issues that were resolved. 
https://github.com/downshiftorg/prophoto-issues/issues/737
https://github.com/downshiftorg/prophoto-issues/issues/725

**Comment by benjamintennant** [comment]
+1 Jay Rowden ticket 188089

**Comment by benjamintennant** [comment]
+1 Andrew Rivera ticket 188320

**Comment by benjamintennant** [comment]
+1 Uri Laitman ticket 188628

**Comment by benjamintennant** [comment]
+1 Lindsey Friar ticket 188908

**Comment by benjamintennant** [comment]
+1 Brady Peterson ticket 189298

**Comment by benjamintennant** [comment]
+1 Helena Goessens ticket 190005

**Comment by benjamintennant** [comment]
+1 Charles Diehle ticket 191015

**Comment by benjamintennant** [comment]
+1 Michael Kormos ticket 191605

**Comment by postmastersteve** [comment]
+1 Paul Willetts ticket 191693

**Comment by benjamintennant** [comment]
+1 Ingar Sørensen ticket 192099

**Comment by postmastersteve** [comment]
+1 Hayley L Adhofer ticket 193196

**Comment by benjamintennant** [comment]
+1 Josef Kohn ticket 193410

**Comment by benjamintennant** [comment]
+1 Robin ticket 198392

**Comment by danjonlam** [comment]
+1 Manuel Gracia ticket 202544

**Comment by benjamintennant** [comment]
+1 Jennifer Jimenez ticket 206245

**Comment by benjamintennant** [comment]
+1 Rochelle Hepworth ticket 206828 - wants alt data on thumbnail galleries

**Comment by benjamintennant** [comment]
+1 Oksana Kuklina ticket 211599

**Comment by danjonlam** [comment]
Are we doing this for graphic modules and tile images? If not, we should add that too,

**Comment by benjamintennant** [comment]
+1 Murray Clarke ticket 216182 - wants grid images to have alt text

**Comment by benjamintennant** [comment]
+1 Tara Arseven wants img alt info on standard excerpt images.
