### ISSUE TITLE
Instagram grid not sizing non-square images properly

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#491]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#183440](https://prophotoblogs.zendesk.com/agent/tickets/183440)
**Priority:** high
**Group:** Developers
**Requester:** anne.deml@web.de
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment">
<p dir="auto">Hello,</p>

<p dir="auto">at the moment I'm working on a new website with Prophoto 7 testdrive. Everything works good, but now I can't work on my visual builder. I get every time a white screen and I see this link (<a href="https://annedeml.de/?pp-visual=1#/" target="_blank" rel="nofollow noreferrer">https://annedeml.de/?pp-visual=1#/</a>) in my browser (Firefox). At first I can see 2-3 seconds the surface of Prophoto 7 and than I get the white screen. In Safari I get a black screen with the Prophoto Logo in the middle.  Now I don't know what I have to do. 
<br>Maybe the fail be connect with the problems to move modules (graphic) in my website content. One of the graphic modul I can't delete at the moment.
<br>Could you help me?</p>

<p dir="auto">Best Anne</p>
</div></blockquote>

**Comment by lalunecreative** [comment]
I've seen this one as well. Instagram grid photos are now just overall blurry because of this issue.
