### ISSUE TITLE
Explore why static build sometimes doesn't include layout CSS

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#495]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#185308](https://prophotoblogs.zendesk.com/agent/tickets/185308)
**Priority:** high
**Group:** Developers
**Requester:** benjamin@pro.photo
**Organization:** Downshift
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment">
<ul dir="auto">
<li>after update to 7.1.5, none of the mobile menus displayed when they were set to always display<br>
</li>
<li>layout background color not applying either until you dirty state and save.</li>
</ul>
<br><br><a href="https://prophotoblogs.zendesk.com/agent/tickets/185168" rel="noreferrer">https://prophotoblogs.zendesk.com/agent/tickets/185168</a><br><br>I'm creating a new ticket because we are talking about lots of things. <br>

<span class="collapse-signature"></span><div class="signature">
<p dir="auto">Benjamin Tennant<br>
ProPhoto Support</p>
<p dir="auto">Follow us for the latest ProPhoto news and updates:<br>
<a href="https://pro.photo/blog/" rel="noreferrer">https://pro.photo/blog/</a></p>
</div>
</div></blockquote>

**Comment by j-arens** [comment]
https://github.com/downshiftorg/prophoto7-issues/issues/504
