### ISSUE TITLE
Embedded grids that were imported from P6 don't display

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#518]
There's a few problems that will need to be resolved here:

The current P6 import process is supposed to convert p6 embedded grid settings in the `wp_options` table to use the same key format we use in P7. That is not happening due to a bug in the import process. https://github.com/downshiftorg/prophoto/issues/3535 will need to solved first.

The embedded grids controller uses an endpoint with a regex that expects grid entity ids to be `UUID`'s. This is not compatible with P6 embedded grids. NOTE: Fixing this issue could cause problems in other areas, specifically should check other parts of the codebase where we query embedded grid data with `get_option`.

We might need to consider users that have already imported from P6. Trying to click edit or delete on their embedded grid placeholders is going break things.

NOTE: Don't forget to re-enable editing and deleting of legacy embedded grids. https://github.com/downshiftorg/prophoto/pull/3537

**Comment by postmastersteve** [comment]
+1 Lori Madeline ticket 186030

**Comment by benjamintennant** [comment]
+1 Katerina ticket 189948

**Comment by benjamintennant** [comment]
+1 Derek Montgomery ticket 190485

**Comment by benjamintennant** [comment]
+1 Paul Tansley ticket 191297

**Comment by benjamintennant** [comment]
+1 Kim Livingood ticket 191246

**Comment by postmastersteve** [comment]
+1 Kate Drennan ticket 193241

**Comment by benjamintennant** [comment]
P6 grid converting seems to not work. 
I added a grid in P6 using classic editor
I activated P7
I try to edit the grid and get this. 
![image](https://user-images.githubusercontent.com/12831291/59384317-ebc44a80-8d2f-11e9-8f79-07c2b5b49a63.png)

**Comment by benjamintennant** [comment]
Weirdly the Royal design I uploaded to ProPhoto 7 appears in <em>"ProPhoto &gt; Manage Designs"</em> in ProPhoto 6. 
![image](https://user-images.githubusercontent.com/12831291/59384653-ab190100-8d30-11e9-95e8-4b50b636ac12.png)

**Comment by benjamintennant** [comment]
Are embedded forms from P6 supposed to import? My form I added to a page in P6 is not importing.
