### ISSUE TITLE
Re-evaluate where we put hamburger/slideout settings

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#541]
The way that the hamburger/slideout settings are split up between the slideout block and the layout is weird and should be re-thought.

https://prophotoblogs.zendesk.com/agent/tickets/186389

**Comment by postmastersteve** [comment]
Zendesk ticket #[186389](https://prophotoblogs.zendesk.com/agent/tickets/186389) has been linked to this issue.

**Comment by postmastersteve** [comment]
closing - duplicate of #339
