### ISSUE TITLE
Optimize and downsize/resize images in tiles and graphic modules

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#545]
Photos and graphics can be uploaded to several areas of ProPhoto 7 which do not get optimized for their use/location in a layout. E.g. a user might upload a logo image into a graphic module at 4000px wide and a large file size, but that logo may appear in a small column which never displays the image larger than about 300px. Browser downsizing makes the graphic look bad in almost all cases.
Also, users must manually select a **2x** or **1/2 size** option to take advantage of the best image quality on high-density screens when this could (should?) be handled automatically base on where the image is placed.

Proposing that we improve our image size management so it is more intelligent and will optimize images for speed and performance, specifically for these layout items:

- graphic module
- tile image layer
- featured image module
- featured background image

Ideally, ProPhoto would automatically use a high 2x resolution size when the uploaded file has enough resolution to fit at 2x where it is being used.

Also, ProPhoto would create downsized copies that are optimized through ImageMagick when the image larger than necessary for where it is being used, feeding the corresponding `srcset` sizes as needed.

**Comment by postmastersteve** [comment]
+1 Emily Henning ticket 186547

**Comment by postmastersteve** [comment]
+1 Jennifer ticket 192051

**Comment by benjamintennant** [comment]
+1 Christina Stangle ticket 192335 - ipad crashing

**Comment by postmastersteve** [comment]
+1 Kevin Gregory ticket 192792

**Comment by danjonlam** [comment]
While this has been tackled to some extent, would still like to re-think the "constrain to 1/2 width' option for graphic modules and tiles. And would like to make sure image downsizing/resizing is also being optimized in the Visual Builder.

**Comment by mdietsche** [comment]
Proposed solutions:

- Tile Layer: There are lots of options for design intent when uploading an image to a tile layer.  I'm thinking image layers should have a "width" or "max-width" option.  When an image is uploaded, the width option should default to the actual image width, or the tile width, whichever is smaller.  This can be adjusted and will help with using srcset and sizes attrs correctly for optimization.
- Graphic module and Featured Image module: We just need to make sure that we're using srcset correctly for these
- Featured Background Image module: There isn't an easy way to optimize a background image.
