### ISSUE TITLE
WordPress content module hides "Header Styles" controls if excerpts are set to grid

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#563]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#186989](https://prophotoblogs.zendesk.com/agent/tickets/186989)
**Priority:** high
**Group:** Developers
**Requester:** arielpyne@gmail.com
**Issue escalated by:** Matt Dietsche

**Comment by postmastersteve** [comment]
+1 Justina Bilodeau ticket 188809

**Comment by postmastersteve** [comment]
+1 Claude Masselot ticket 189024

**Comment by postmastersteve** [comment]
+1 Amy Kimball ticket 189244

**Comment by postmastersteve** [comment]
+1 cedric ticket 189095

**Comment by benjamintennant** [comment]
duplicate of #604 and #295

**Comment by postmastersteve** [comment]
closing - duplicate of #604
