### ISSUE TITLE
Show galleries from gallery page type in Visual Builder 

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#595]
When viewing the gallery custom post type in the Visual Builder you don't see the gallery, or even a gallery placeholder. Add the ability for the gallery to display or, at the least, show a placeholder.

**Comment by benjamintennant** [comment]
+1 Stephanie Ruppert ticket 188102

**Comment by benjamintennant** [comment]
+1 Heather DeCamp ticket 188133

**Comment by benjamintennant** [comment]
+1 Virginia Schultz ticket 188227

**Comment by benjamintennant** [comment]
+1 Aimee Haak ticket 189349

**Comment by benjamintennant** [comment]
+1 Allison Williams ticket 189557

**Comment by benjamintennant** [comment]
+1 Anna Wisjo ticket 189936

**Comment by benjamintennant** [comment]
+1 Morgan ticket 190300

**Comment by benjamintennant** [comment]
+1 Leandra Romines ticket 190612

**Comment by benjamintennant** [comment]
+1 Fritz Liedtke ticket 190803

**Comment by postmastersteve** [comment]
+1 jessica hunt ticket 191530

**Comment by postmastersteve** [comment]
+1 Brittany Drabant ticket 190746

**Comment by postmastersteve** [comment]
+1 Christina Tuttle ticket 191133

**Comment by postmastersteve** [comment]
+1 Jana Lubbe ticket 190989

**Comment by postmastersteve** [comment]
+1 Amy Carr ticket 190364

**Comment by postmastersteve** [comment]
+1 Charles Diehle ticket 190253

**Comment by postmastersteve** [comment]
+1 Jessica Hamlin ticket 191596

**Comment by postmastersteve** [comment]
+1 Heather Swanner ticket 191730

**Comment by postmastersteve** [comment]
+1 Hurst Gannon ticket 191965

**Comment by benjamintennant** [comment]
+1 Karen Stauffer ticket 192754

**Comment by benjamintennant** [comment]
+1 samie lee ticket 192755

**Comment by benjamintennant** [comment]
+1 Trudy Joubert ticket 193067

**Comment by postmastersteve** [comment]
+1 Laura Stone ticket 192535

**Comment by postmastersteve** [comment]
+1 Isabel ticket 193439

**Comment by postmastersteve** [comment]
+1 Isabel ticket 193439
