### ISSUE TITLE
ProPhoto 7 form log needs to be paginated

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#611]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#188378](https://prophotoblogs.zendesk.com/agent/tickets/188378)
**Priority:** high
**Group:** Developers
**Requester:** steve@pro.photo
**Organization:** Downshift
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment">ProPhoto 6 was updated to <i>paginate</i> contact form logs to reduce the payload size when fetching these items.<br>ProPhoto 7 does not have pagination support, and so loads the <i>ProPhoto &gt; Form Log</i> screen without <b>any</b> entries if the number/payload exceeds limits.<br><br>Users are left to assume there have been no form submissions. (!!)<br>

<span class="collapse-signature"></span><div class="signature">
<p dir="auto">Steve Post<br>
ProPhoto Support</p>
<p dir="auto">Follow us for the latest ProPhoto news and updates:<br>
<a href="https://www.twitter.com/prophotoblogs/" rel="noreferrer">https://www.twitter.com/prophotoblogs/</a></p>
</div>
</div></blockquote>

**Comment by benjamintennant** [comment]
+1 Jeff Hammond ticket 189263

**Comment by j-arens** [comment]
This was fixed in 7.5, can this issue be closed?
