### ISSUE TITLE
Default WooCommerce layout applied to all page in VB

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#627]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#188365](https://prophotoblogs.zendesk.com/agent/tickets/188365)
**Priority:** high
**Group:** Developers
**Requester:** olesyared@gmail.com
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment">
<p dir="auto">This is a follow-up to your previous request <a href="/agent/tickets/187843" target="_blank" rel="ticket">#187843</a> "I am trying to Import my de..."</p>

<p dir="auto">Hello, I am getting an error while trying to edit my gallery pages and WordPress support team concluded that the problem was due to the ProPhoto Theme. Please help!
<br>Below is the last email from Wordpress support team.
<br>Thank you!</p>

<p dir="auto">Hello Olesya,</p>

<p dir="auto">Thank you for getting back to us.</p>

<p dir="auto">I can understand your concern regarding this issue. I have logged in to admin panel of website at <a href="https://www.zestyorangephoto.com/wp-admin" target="_blank" rel="nofollow noreferrer">https://www.zestyorangephoto.com/wp-admin</a> with provided login details and able to replicate issue with editing pages under Galleries ( Family, Maternity, Newborn ) . It is loading with 'Internal server error' .</p>

<p dir="auto">I didn't find any recent error logs generated for this website at <a href="https://www1.ipage.com/controlpanel/cgiManagement/cgierrorlog.html" target="_blank" rel="nofollow noreferrer">https://www1.ipage.com/controlpanel/cgiManagement/cgierrorlog.html</a> . So, i have tried enabled debug mode for this Wordpress website inside wp-config.php file.</p>

<p dir="auto">Now, when editing above 3 pages, it is displaying error:
<br>Fatal error: Uncaught RuntimeException: ViewContext accessed before data set. in /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php:288 Stack trace: <a href="/agent/tickets/0" target="_blank" rel="ticket">#0</a> /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php(165): ProPhoto\Front\Services\View\ViewContext-&gt;get(Array) <a href="/agent/tickets/1" target="_blank" rel="ticket">#1</a> /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/front/View/ResolvesGalleryComponentsTrait.php(36): ProPhoto\Front\Services\View\ViewContext-&gt;getGalleryStyle(NULL) <a href="/agent/tickets/2" target="_blank" rel="ticket">#2</a> /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/prophoto/Middleware/GalleryMiddleware.php(123): ProPhoto\Middleware\GalleryMiddleware-&gt;resolveGalleryStyle(Object(ProPhoto\Front\Services\View\ViewContext), NULL) <a href="/agent/tickets/3" target="_blank" rel="ticket">#3</a> /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-includes/shortcodes.php(319): ProPhoto\Middleware\GalleryMiddleware-&gt;renderGalleryFromShortCode(Array, '', 'pp_gallery') <a href="/agent/tickets/4" target="_blank" rel="ticket">#4</a> [internal function]: do_shortcode_tag(Array) <a href="/agent/tickets/5" target="_blank" rel="ticket">#5</a> /hermes/bosnaw in /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php on line 288</p>

<p dir="auto">These errors are related to theme 'prophoto7' set for this website. I recommend you to contact theme support regarding this issue. URL at <a href="https://www.zestyorangephoto.com/info.php" target="_blank" rel="nofollow noreferrer">https://www.zestyorangephoto.com/info.php</a> shows PHP settings enabled for your account.</p>

<p dir="auto">Please feel free to reply to this email if you have any further questions, we are happy to help you.</p>

<p dir="auto">Sincerely,</p>

<p dir="auto">Suresh K
<br>Senior Technical Specialist</p>
</div></blockquote>

**Comment by postmastersteve** [comment]
+1 Karen Ketels ticket 191535

**Comment by benjamintennant** [comment]
+1 Rebecca Thompson ticket 191684

**Comment by postmastersteve** [comment]
+1 Northfolk ticket 192497

**Comment by benjamintennant** [comment]
+1 Annemarie Gruden ticket 192277

**Comment by benjamintennant** [comment]
+1 Michael Kormos

**Comment by postmastersteve** [comment]
+1 Amanda Sloane ticket 193405

**Comment by benjamintennant** [comment]
+1 Courtney Keim ticket 194101
