### ISSUE TITLE
confirm/warn when changing default layout

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#644]

**Comment by postmastersteve** [comment]
+1 Sharon Ward ticket 191160

**Comment by postmastersteve** [comment]
+1 carrie guggenmos ticket 191227

**Comment by postmastersteve** [comment]
+1 Marie Clark ticket 191108

**Comment by postmastersteve** [comment]
+1 Denoya Gomez ticket 190937

**Comment by postmastersteve** [comment]
+1 Jamilla Yipp ticket 191779

**Comment by postmastersteve** [comment]
+1 Nicole Saunders ticket 192054

**Comment by postmastersteve** [comment]
+1 Kelly Anderson ticket 192175

**Comment by postmastersteve** [comment]
+1 Lauren Sellari ticket 192181

**Comment by postmastersteve** [comment]
+1 Jill Knight ticket 192021

**Comment by postmastersteve** [comment]
+1 Kristina Cazares ticket 192580

**Comment by postmastersteve** [comment]
+1 Jana Buskova ticket 192818

**Comment by postmastersteve** [comment]
+1 Hayley L Adhofer ticket 192941

**Comment by postmastersteve** [comment]
+1 Emily Davison ticket 193027

**Comment by postmastersteve** [comment]
+1 Jennifer Eggers ticket 193395

**Comment by postmastersteve** [comment]
+1 Hailey Gonya ticket 193463

**Comment by postmastersteve** [comment]
+1 Mike Cook ticket 193512
