### ISSUE TITLE
WP Customizer errors in some cases

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#646]
Removing sections from WP Customizer causes JS errors in some cases.  Not sure of the root cause, but could be when customizer option values were already set.

**Comment by postmastersteve** [comment]
Zendesk ticket #[189251](https://prophotoblogs.zendesk.com/agent/tickets/189251) has been linked to this issue.

**Comment by postmastersteve** [comment]
Zendesk ticket #[189606](https://prophotoblogs.zendesk.com/agent/tickets/189606) has been linked to this issue.
