### ISSUE TITLE
Allow ProPhoto Image handling to work with images off server

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#660]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#189901](https://prophotoblogs.zendesk.com/agent/tickets/189901)
**Priority:** high
**Group:** Developers
**Requester:** elizabethgrace31@gmail.com
**Assignee:** Matt Dietsche
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment"><p dir="auto">Hey the "on the blog" grid on my front page is no longer displaying the featured images from those posts and just showing the same one for them all. I checked and each post definitely does have a featured image designated and they used to all be displayed on the front page. <a href="https://youisalpha.com" target="_blank" rel="nofollow noreferrer">https://youisalpha.com</a></p></div></blockquote>

**Comment by meatwad5675** [comment]
The symptom here is that images that are caught by Jetpack's image load time enhancement feature aren't displayed by ProPhoto grids.  This is because ProPhoto currently rejects an image url that it can't convert to a valid path that it can find on the server.  Maybe we can adjust things that consume our Image model to always try to serve the original image if we can't find it in the file system.

**Comment by postmastersteve** [comment]
+1 Sara Rosenberger ticket 191072

**Comment by postmastersteve** [comment]
+1 Arlene Briones ticket 191071

**Comment by postmastersteve** [comment]
+1 Melissa Gibson ticket 192890
using Jetpack _site accelerator_ feature to speed up image load times
breaks grid thumbnails

**Comment by postmastersteve** [comment]
+1 narelle ticket 193444
using Jetpack _site accelerator_ feature to speed up image load times:
http://screenshots.pro.photo/2019-04-16_16-25-41.png 
breaks grid thumbnails

**Comment by postmastersteve** [comment]
+1 Kit Haselden ticket 194285
using Jetpack site accelerator feature to speed up image load times

**Comment by benjamintennant** [comment]
+1 radiant photography - wants to use jetpack image accelerator which Tiled Galleries requires.

**Comment by danjonlam** [comment]
ProPhoto no longer creates/uses its own downsized images, so this is no longer an issue.
