### ISSUE TITLE
Mobile menu position problems when WP Admin bar is present

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#677]
We have a media query that sets the position of the hamburger to absolute instead of fixed at 782px. I think this was done because the wp-admin bar used to be sticky. We need to remove the absolute positioning and keep it at fixed.

**Comment by benjamintennant** [comment]
+1 Rob Hooper ticket 191744

**Comment by benjamintennant** [comment]
+1 Hélio Cristóvão ticket 192341 - mobile menu scrolls and disappears

**Comment by benjamintennant** [comment]
+1 caroline bates ticket 192019 - confused whey the mobile menu is scrolling and not sticking

**Comment by j-arens** [comment]
Duplicate of https://github.com/downshiftorg/prophoto7-issues/issues/224
