### ISSUE TITLE
Images are added incorrectly in the WP Media Library when they are not found

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#689]
When ProPhoto encounters an image during page load, the downsizing process appears to check for an original image in the WordPress file system and Media Library. If it locates the file on the server but not the Media Library entry, ProPhoto adds the image to the library so it can find/generate downsized copies.

However, it appears to make a couple mistakes.

1. When adding an image to the library, the title of the record is appended by ProPhoto with a UNIX timestamp code - e.g. if an image had a filename like `0I6A1574-2.jpg` the media library should use `0I6A1574-2` for the media item **post_name** and **post_title** fields. But ProPhoto alters **post_name** by appending a timestamp, resulting in data like `0i6a1574-21532803697` being added instead. It seems this was to prevent conflicts when a record already exists with the same file name, but this appears to be entirely unnecessary. WordPress seems to manage and prevent conflicts via another mechanism than the post_name value, so ProPhoto probably shouldn't alter this data.
2. WordPress doesn't seem to generate the thumbnail or other standard sizes if the GUID of the new entry does not match the site URL. ProPhoto appears to store new records without the proper **protocol** in some cases, causing a mismatch and a media library entry without a thumbnail. (which ProPhoto may not have needed to add at all) E.g., when WP has been updated to use https:// in the site address, but the site is hit using http:// and no redirect or _Really Simple SSL_ plugin is present to force to the secure address.

Missing thumbnails in the media library—as well as the duplicate entries ProPhoto creates by mistake—might come down to simply failing to accessing media using the same URL as the site is setup for (instead of based on the request/hit) and then accidentally storing the GUID based on the request/hit instead of the site URL.

**Comment by postmastersteve** [comment]
+1 Wendy Cain ticket 190452

**Comment by postmastersteve** [comment]
+1 Sharon Ward ticket 191160

**Comment by danjonlam** [comment]
ProPhoto  no longer creating downsized images, so this is no longer an issue.
