### ISSUE TITLE
Grids can't use externally hosted images

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#743]
A common example is a recent posts grid where the featured images are being served from a CDN. Because the image isn't physically on the server prophoto can't generate relevant image data and uses the fallback which is not desirable. We should try to rework grids so that they can simply use the url to the external image instead of bailing completely.

In `PostImageFinder.php` line 94

```php
    /**
     * Create an image from id and uri
     *
     * Updates the uri and also sets the path if possible
     *
     * @param string $id
     * @param string $uri
     * @return Image|null
     */
    public function createImage($id, $uri)
    {
        $updatedUri = $this->uriUpdater->update($uri);
        $path = $this->convert->urlToPath($updatedUri);
        if (! $path || ! file_exists($path)) {
            return null;
        }

        $image = $this->imageFactory->create($id, '', $updatedUri);
        $image->setPath($path);
        $image->setExists(true);

        return $image;
    }
```

**Comment by benjamintennant** [comment]
+1 Mark Johansson ticket 198615 - wants to use JetPack CDN

**Comment by danjonlam** [comment]
P8 is now utilizing WordPress source set images, not ProPhoto downsized images. So we just need to ensure the grid thumbnails are compatible with WPE CDN options.

**Comment by mdietsche** [comment]
This works now in ProPhoto 8
