### ISSUE TITLE
Add responsive embed support to ProPhoto for WordPress 5

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#761]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#193338](https://prophotoblogs.zendesk.com/agent/tickets/193338)
**Priority:** normal
**Group:** Developers
**Requester:** steve@pro.photo
**Organization:** Downshift
**Issue escalated by:** Josh Arens

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto">Adds support for responsive embeds (e.g. YouTube embed blocks, etc.):<br><pre style="white-space: pre-wrap">add_theme_support( 'responsive-embeds' );<br></pre>I'd like this for our help site at the least.<br>

<span class="collapse-signature"></span><div class="signature">
<p dir="auto">Steve Post<br>
ProPhoto Support</p>
<p dir="auto">Follow us for the latest ProPhoto news and updates:<br>
<a href="https://pro.photo/blog/" rel="noreferrer">https://pro.photo/blog/</a></p>
</div>
</div></blockquote>

**Comment by lalunecreative** [comment]
We need this video in P7 pretty bad too.

**Comment by postmastersteve** [comment]
+1 Ulli Schlapka ticket 195962

**Comment by postmastersteve** [comment]
duplicate of #734
