### ISSUE TITLE
row/column customizations on modules for convienence

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#94]
<a href="https://github.com/Ramshackle-Jamathon"><img src="https://avatars3.githubusercontent.com/u/5943242?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Ramshackle-Jamathon](https://github.com/Ramshackle-Jamathon)**
_Monday Feb 12, 2018 at 22:43 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/2579_

----

Steve: "It is not intuitive that you must play with column "widget alignment" settings to get a group of images in a graphics module to appear centered as a group. I propose that we expose some alignment controls within the graphics widget, maybe the `justify-content` properties? - left (`flex-start`), center, right (`flex-end`), fill (`space-between`), and distribute (`space-around`) would really help people get the look they're after without needing CSS from us.

Users currently have to make the cognitive leap that you must apply alignment within the column's settings, which is counterintuitive and prevents you from achieving alignments you might want. 
(e.g. a graphics widget that is left-aligned followed by one that is centered, all in the same column)
"

**Comment by meatwad5675** [comment]
<a href="https://github.com/Ramshackle-Jamathon"><img src="https://avatars3.githubusercontent.com/u/5943242?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Ramshackle-Jamathon](https://github.com/Ramshackle-Jamathon)**
_Monday Feb 12, 2018 at 22:45 GMT_

----

more steve: "I find myself really wishing there were padding controls for each module itself so that I can be in the context of editing a module to get the position and spacing I want from other items in the layout. 

Have we considered the ability to add at least top/bottom padding to modules so you can move them arbitrarily away from other modules in a column? Otherwise, all the widgets in my column need to have the same spacing from the column's settings. (which works, but requires me to realize that I have to adjust module spacing within a column's options)
"

**Comment by postmastersteve** [comment]
closing - modules can (almost all) be left, center, right aligned.
