### ISSUE TITLE
Tile sorting + searching?

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#98]
<a href="https://github.com/Ramshackle-Jamathon"><img src="https://avatars3.githubusercontent.com/u/5943242?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Ramshackle-Jamathon](https://github.com/Ramshackle-Jamathon)**
_Monday Feb 12, 2018 at 23:08 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/2592_

----

Steve : 'There is still no rhyme or reason to the tile sort order in the Tiles pane. (probably UUID?) 
Please sort that sidebar by title or last-edited timestamp or give me search so things are easier to find over there.  😉   Some designs have dozens of tiles to deal with...'

**Comment by meatwad5675** [comment]
<a href="https://github.com/postmastersteve"><img src="https://avatars3.githubusercontent.com/u/275742?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [postmastersteve](https://github.com/postmastersteve)**
_Monday May 21, 2018 at 19:15 GMT_

----

Zendesk ticket #[177178](https://prophotoblogs.zendesk.com/agent/tickets/177178) has been linked to this issue.

**Comment by meatwad5675** [comment]
<a href="https://github.com/postmastersteve"><img src="https://avatars3.githubusercontent.com/u/275742?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [postmastersteve](https://github.com/postmastersteve)**
_Monday May 21, 2018 at 19:15 GMT_

----

*Comment made from Zendesk by Matt Dietsche on 2018-05-21 at 19:15:*

<blockquote><div class="zd-comment">Connected this ticket to an existing issue in our system.<br>

<span class="collapse-signature"></span><div class="signature">
<p>Matt Dietsche<br>
ProPhoto Support</p>
<p>Follow us for the latest ProPhoto news and updates:<br>
<a href="https://www.twitter.com/prophotoblogs/" rel="noreferrer">https://www.twitter.com/prophotoblogs/</a></p>
</div>
</div></blockquote>

**Comment by postmastersteve** [comment]
closing - tile library is currently sorted by title
